/* Calculus — PWA shell.
   Reads index.json (generated by admin/pwa/deploy.py) and presents it as the
   "Binder": a rail of units and lessons, a reader that never navigates away.

   Two decisions that are load-bearing, both documented in
   admin/reference/student_site_plan.md 8:

   1. Documents are addressed by CONTENT: q/foo.html?h=<hash>.  A changed
      document is therefore a different URL, so a plain cache-first service
      worker is always correct and there is no hash bookkeeping anywhere.
   2. The four documents of the open lesson are mounted at once and toggled by
      visibility, never torn down.  Destroying an iframe reloads it, which would
      reset every slider in a Quarto's interactives.
*/
'use strict';

const CACHE_DOCS = 'calc-docs-v1';
const VIEWS = [
  { id: 'quarto',   label: 'Quarto',      hint: 'the full write-up, with the interactives' },
  { id: 'packet',   label: 'Packet',      hint: 'the questions you worked in class' },
  { id: 'ticket',   label: 'Entry ticket', hint: '' },
  { id: 'onepager', label: 'One-pager',   hint: 'the keeper' },
];
const KEYS = [
  ['/', 'Search'], ['&uarr; &darr;', 'Move between lessons'], ['&crarr;', 'Open'],
  ['Tab', 'Next document'], ['&#8984;B', 'Retract the sidebar'], ['F', 'Full screen'],
  ['G', 'Unit guide'], ['U', 'Next unit'], ['Esc', 'Back out'], ['?', 'This list'],
];

const $ = s => document.querySelector(s);
const el = (t, c, h) => { const n = document.createElement(t); if (c) n.className = c;
                          if (h != null) n.innerHTML = h; return n; };
const esc = s => String(s).replace(/[&<>"]/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;' }[c]));

const S = {                       // application state
  data: null, units: [], lessons: [], guideFor: new Map(),
  ui: 0, li: 0, view: 'quarto', mode: 'doc',
  slim: localStorage.getItem('slim') === '1',
  open: new Set(JSON.parse(localStorage.getItem('open') || '[]')),
  full: false, offline: false, cached: new Set(), hits: [], hi: 0,
  // Freshness.  The pill used to read "Up to date" whenever navigator.onLine
  // was true, which said nothing about whether the manifest was current -- an
  // app left docked and open never noticed a publish at all.
  fingerprint: '', lastCheck: 0, pending: false, checking: false,
};

/* ══════════════════════════════════════════════════════════ data ══ */

const docURL = d => d ? `${d.file}?h=${d.hash.slice(0, 12)}` : null;

/** A cheap identity for the whole manifest: every lesson's slug and every
 *  document hash.  Documents are content-addressed, so a changed hash IS a
 *  changed document -- this catches a new lesson AND a re-rendered one. */
function fingerprint(j) {
  const out = [];
  for (const u of (j.units || []))
    for (const L of (u.lessons || [])) {
      out.push(L.slug, L.quarto ? L.quarto.hash : '-');
      for (const k of Object.keys(L.docs || {}).sort()) out.push(k, L.docs[k].hash);
    }
  return out.join('|');
}

const ago = t => {
  const m = Math.floor((Date.now() - t) / 60000);
  if (m < 1)  return 'just now';
  if (m < 60) return m + ' min ago';
  const h = Math.floor(m / 60);
  return h < 24 ? h + ' h ago' : Math.floor(h / 24) + ' d ago';
};

function viewsOf(L) {
  return VIEWS.map(v => ({ ...v, doc: v.id === 'quarto' ? L.quarto : L.docs[v.id] }));
}

/** Pair each lesson with its row in the unit guide.  The guide is authoritative
 *  for Stewart sections and homework — some Quartos' <meta name="lesson"> carries
 *  the folder code rather than the textbook section. */
function linkGuide(unit) {
  for (const L of unit.lessons) {
    const code = L.code.replace(/^L/, '');
    const row = (unit.guide || []).find(r => r.kind === 'lesson' &&
      (r.name || '').replace(/\s+/g, ' ').trim().startsWith(code + ' '));
    if (row) {
      S.guideFor.set(L, row);
      L.stewart = row.stewart || L.stewart;
      L.date = row.date;
    }
  }
}

async function load() {
  let json;
  try {
    const r = await fetch('index.json', { cache: 'no-cache' });
    if (!r.ok) throw new Error(r.status);
    S.offline = r.headers.get('X-From-Cache') === '1';
    json = await r.json();
  } catch (e) {
    const c = await caches.match('index.json');
    if (!c) {
      $('#bootmsg').textContent = navigator.onLine
        ? 'Could not load the course. Try again in a moment.'
        : 'You are offline, and this device has not downloaded the course yet. Connect once and it will work offline afterwards.';
      return;
    }
    json = await c.json();
    S.offline = true;
  }
  S.data = json;
  S.fingerprint = fingerprint(json);
  S.lastCheck = Date.now();
  S.units = json.units || [];
  S.units.forEach(linkGuide);
  S.lessons = S.units.flatMap(u => u.lessons.map(L => ({ L, u })));
  if (!S.lessons.length) {
    $('#bootmsg').textContent = S.offline
      ? 'Nothing downloaded on this device yet. Reconnect once.'
      : 'No lessons published yet.';
    return;
  }

  // Default: expand the unit you were last in, or the newest one. Collapsed
  // units keep the rail short once the year has five of them.
  if (!S.open.size) S.open.add(S.units[S.units.length - 1].unit);

  const last = JSON.parse(localStorage.getItem('last') || 'null');
  if (last) {
    const i = S.lessons.findIndex(x => x.L.slug === last.slug);
    if (i >= 0) {
      S.li = i; S.ui = S.units.indexOf(S.lessons[i].u); S.view = last.view || 'quarto';
      S.open.add(S.lessons[i].u.unit);
    }
  }
  await refreshCached();
  $('#boot').remove();
  render();
}

/** Re-read the manifest and say so if it moved.  Called when the window comes
 *  back to the front and when the network returns -- load() runs once at boot,
 *  so without this a running app is frozen at whatever was published the moment
 *  it started. */
async function checkForUpdates(force) {
  if (S.checking || S.pending) return;
  if (!navigator.onLine) { S.offline = true; renderNet(); return; }
  if (!force && S.lastCheck && Date.now() - S.lastCheck < 60000) return;
  S.checking = true;
  try {
    const r = await fetch('index.json', { cache: 'no-cache' });
    if (!r.ok) throw new Error(r.status);
    // The worker served its cached copy, so this was not a real check.
    if (r.headers.get('X-From-Cache') === '1') { S.offline = true; return; }
    const j = await r.json();
    S.offline = false;
    S.lastCheck = Date.now();
    if (fingerprint(j) !== S.fingerprint) {
      S.pending = true;
      toast('New lessons are available.');
    }
  } catch (e) {
    S.offline = true;        // say the check failed rather than claim freshness
  } finally {
    S.checking = false;
    renderNet();
  }
}

async function refreshCached() {
  S.cached = new Set();
  if (!('caches' in window)) return;
  try {
    const c = await caches.open(CACHE_DOCS);
    // Key on path AND hash, exactly as the worker does.  Stripping the query
    // made a RE-RENDERED document report as saved while only its previous
    // version was cached -- the rail's dot went green and the button said
    // "Saved for offline" for a file that was not there.
    for (const req of await c.keys()) {
      const u = new URL(req.url);
      S.cached.add(ckey(u.pathname.split('/').slice(-2).join('/') + u.search));
    }
  } catch (e) { /* private mode */ }
}

/** Both key derivations run through this, because they read the same name from
 *  two places that encode it differently: cacheKey() gets the RAW string out of
 *  index.json, refreshCached() gets a URL pathname, which is percent-encoded.
 *  `q/2-1-min-max values.html` vs `q/2-1-min-max%20values.html` could never
 *  compare equal, so every Unit 2 document reported itself unsaved forever --
 *  the rail dot stayed pale and the button never flipped to "Saved for
 *  offline", while the files were in fact downloaded and available offline.
 *  deploy.py no longer publishes such a name; decoding here means a stray
 *  space, `+` or accent can never desync the two again. */
const ckey = s => { try { return decodeURIComponent(s); } catch (e) { return s; } };
const cacheKey = d => ckey(`${d.file.split('/').slice(-2).join('/')}?h=${d.hash.slice(0, 12)}`);
const isCached = d => d && S.cached.has(cacheKey(d));

/* ══════════════════════════════════════════════════════════ rail ══ */

function render() {
  document.body.classList.toggle('slim', S.slim);
  document.body.classList.toggle('full', S.full);
  renderRail(); renderFoot(); renderReader(); renderNet();
}

function renderRail() {
  const wide = $('#wide'), slim = $('#slim');
  wide.innerHTML = ''; slim.innerHTML = '';

  S.units.forEach((u, ui) => {
    const open = S.open.has(u.unit);
    const onGuide = S.mode === 'guide' && ui === S.ui;

    const head = el('button', 'unithead',
      `<b><span class="chev${open ? ' open' : ''}">
         <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.6"><path d="M9 6l6 6-6 6"/></svg>
       </span>${esc(unitTitle(u))}</b>
       <span>${open ? '' : u.lessons.length + (u.lessons.length === 1 ? ' lesson' : ' lessons')}</span>`);
    head.onclick = () => {
      S.open.has(u.unit) ? S.open.delete(u.unit) : S.open.add(u.unit);
      localStorage.setItem('open', JSON.stringify([...S.open]));
      renderRail();
    };
    wide.appendChild(head);

    // slim rail: a unit chip that also toggles, then that unit's codes
    const chip = el('button', 'uchip' + (open ? ' open' : ''), esc('U' + (u.unit.match(/\d+/) || ['?'])[0]));
    chip.onclick = head.onclick;
    tipify(chip, unitTitle(u), open ? 'click to collapse' : `${u.lessons.length} lessons — click to expand`);
    slim.appendChild(chip);

    if (!open) { slim.appendChild(el('div', 'sep')); return; }

    const g = el('button', 'lrow' + (onGuide ? ' on' : ''),
      `<span class="lcode" style="display:grid;place-items:center;padding-top:0">
         <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M4 5h16v14H4z"/><path d="M4 10h16M4 15h16"/></svg>
       </span>
       <span class="lmeta"><span class="ltitle">Unit guide</span>
       <span class="lsub">every day, every problem</span></span>`);
    g.onclick = () => { S.ui = ui; S.mode = 'guide'; render(); };
    wide.appendChild(g);

    const gi = el('button', 'srow' + (onGuide ? ' on' : ''),
      `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 5h16v14H4z"/><path d="M4 10h16M4 15h16"/></svg>`);
    gi.onclick = g.onclick;
    tipify(gi, 'Unit guide', unitTitle(u));
    slim.appendChild(gi);
    slim.appendChild(el('div', 'sep'));

    (u.guide && u.guide.length ? u.guide : u.lessons.map(L => ({ kind: 'lesson', _L: L })))
      .forEach(row => railRow(u, row, wide, slim));
    slim.appendChild(el('div', 'sep'));
  });
}

function railRow(u, row, wide, slim) {
  if (row.kind === 'break') {
    wide.appendChild(el('div', 'brk', esc(row.text || '')));
    slim.appendChild(el('div', 'sep'));
    return;
  }
  if (row.kind === 'banner') return;

  if (row.kind !== 'lesson') {                       // quiz / review / exam
    const exam = row.kind === 'exam';
    wide.appendChild(el('div', 'assess' + (exam ? ' exam' : ''),
      `<span>${esc(row.name)}</span><span style="opacity:.6;font-weight:400">${esc(row.date || '')}</span>`));
    const b = el('div', 'srow', `<span class="sbar${exam ? ' exam' : ''}"></span>`);
    tipify(b, row.name, row.date || '');
    slim.appendChild(b);
    return;
  }

  const L = row._L || S.lessons.find(x => x.u === u && S.guideFor.get(x.L) === row)?.L;
  if (!L) {                                          // scheduled, not published yet
    wide.appendChild(el('div', 'assess',
      `<span style="color:var(--ink-4);font-weight:400">${esc(row.name)}</span>
       <span style="opacity:.5;font-weight:400">${esc(row.date || '')}</span>`));
    slim.appendChild(el('div', 'srow', `<span class="sbar" style="background:#eef2f6"></span>`));
    return;
  }

  const i = S.lessons.findIndex(x => x.L === L);
  const on = S.mode === 'doc' && i === S.li;
  const ok = isCached(L.quarto);
  const r = el('button', 'lrow' + (on ? ' on' : ''),
    `<span class="lcode">${esc(L.code)}</span>
     <span class="lmeta"><span class="ltitle">${esc(L.title)}</span>
     <span class="lsub">${esc(L.stewart ? '§' + L.stewart.replace(/^§/, '') : '')}</span></span>
     <span class="dot ${ok ? '' : 'pale'}" style="margin-top:5px"></span>`);
  r.onclick = () => pick(i);
  wide.appendChild(r);

  const s = el('button', 'srow' + (on ? ' on' : ''),
    `<span class="scode">${esc(L.code.replace(/^L/, ''))}</span><span class="dot ${ok ? '' : 'pale'}"></span>`);
  s.onclick = () => pick(i);
  tipify(s, L.title, `${L.code}${L.stewart ? ' · §' + L.stewart.replace(/^§/, '') : ''}`);
  slim.appendChild(s);
}

/** "unit1-review" -> "Unit 1 · Review",
 *  "unit2-applications_of_derivatives" -> "Unit 2 · Applications of Derivatives".
 *  The guide's banner is the subtitle, not the title — it is a full sentence and
 *  reads as shouting in the rail.
 *
 *  Separators have to be turned into spaces BEFORE title-casing: `_` is a word
 *  character, so \b never fires after one and the old version shipped
 *  "Applications_of_derivatives" straight into the rail. */
const UNIT_SMALL = new Set(['of', 'the', 'and', 'a', 'an', 'to', 'in', 'for', 'at', 'by', 'from', 'on', 'vs']);
const unitCase = s => s.split(/\s+/).filter(Boolean)
  .map((w, i) => (i && UNIT_SMALL.has(w.toLowerCase()))
    ? w.toLowerCase()
    : w.charAt(0).toUpperCase() + w.slice(1))
  .join(' ');
const unitTitle = u => u.unit.replace(/^unit(\d+)-?/, 'Unit $1 · ')
  .split('·').map(s => unitCase(s.trim().replace(/[_-]+/g, ' '))).join(' · ');
const unitSub = u => ((u.guide || []).find(r => r.kind === 'banner')?.text || '')
  .replace(/^REVIEW:\s*/i, '').trim();

/** The rail scrolls, so an absolutely-positioned tooltip inside it is clipped
 *  by overflow-x.  One shared fixed element, positioned on hover, instead. */
function tipify(node, title, sub) {
  node.onmouseenter = () => {
    if (!S.slim) return;
    const t = $('#tip'), r = node.getBoundingClientRect();
    t.innerHTML = `<b>${esc(title)}</b><span>${esc(sub)}</span>`;
    t.style.display = 'block';
    t.style.left = (r.right + 10) + 'px';
    t.style.top = Math.max(8, r.top + r.height / 2 - t.offsetHeight / 2) + 'px';
  };
  node.onmouseleave = () => { $('#tip').style.display = 'none'; };
}

function renderFoot() {
  const u = S.units[S.ui];
  const files = u.lessons.flatMap(L => [L.quarto, ...Object.values(L.docs)]);
  // Only what is actually missing.  Documents are content-addressed, so an
  // unchanged file is already a cache hit and costs nothing -- quoting the
  // whole unit's size after a one-lesson publish read as "re-download 45 MB",
  // which is not what happens.
  const missing = files.filter(f => !isCached(f));
  S.savedAll = missing.length === 0;
  const mb = missing.reduce((a, f) => a + f.bytes, 0) / 1e6;
  const size = mb < 1 ? mb.toFixed(1) : mb.toFixed(0);
  const partial = missing.length > 0 && missing.length < files.length;
  const b = $('#savebtn');
  b.innerHTML = S.savedAll
    ? `<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 6L9 17l-5-5"/></svg> Saved for offline`
    : `<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 3v12m0 0l-4-4m4 4l4-4M4 19h16"/></svg> ${partial ? 'Save what&rsquo;s new' : 'Save this unit'} <small>${size} MB</small>`;
  b.disabled = S.savedAll;
  b.onclick = () => saveUnit(u, missing);
}

async function saveUnit(u, files) {
  const b = $('#savebtn');
  b.disabled = true;
  let done = 0;
  for (const f of files) {
    try { await fetch(docURL(f)); } catch (e) { /* keep going */ }
    done++;
    b.innerHTML = `Saving&hellip; <small>${done} of ${files.length}</small>`;
  }
  await refreshCached();
  render();
}

/* ════════════════════════════════════════════════════════ reader ══ */

function renderReader() {
  $('#pane').hidden = S.mode !== 'guide';
  $('#frames').style.display = S.mode === 'guide' ? 'none' : '';
  $('#dochead').style.display = S.mode === 'guide' ? 'none' : '';
  if (S.mode === 'guide') { renderGuide(); return; }

  const { L } = S.lessons[S.li];
  const vs = viewsOf(L);
  if (!vs.find(v => v.id === S.view && v.doc)) S.view = 'quarto';

  const head = $('#dochead');
  head.innerHTML = '';
  head.appendChild(el('div', 'crumb', esc(unitTitle(S.lessons[S.li].u))));
  head.appendChild(el('h1', 'doc', esc(L.title)));
  head.appendChild(el('div', 'docmeta',
    `<b>${esc(L.code)}</b><span>&middot;</span>${L.stewart ? '<span>§' + esc(L.stewart.replace(/^§/, '')) + '</span><span>&middot;</span>' : ''}
     <span>${esc(L.date || '')}</span>`));

  const bar = el('div', 'toolbar');
  const seg = el('div', 'seg');
  vs.forEach(v => {
    const b = el('button', v.id === S.view ? 'on' : '', esc(v.label));
    b.disabled = !v.doc;
    b.title = v.doc ? v.hint : 'not published';
    b.onclick = () => setView(v.id);
    seg.appendChild(b);
  });
  bar.appendChild(seg);
  bar.appendChild(el('kbd', '', 'Tab'));

  const right = el('div', 'spacer');
  const fs = el('button', 'linkbtn',
    `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 9V4h5M20 9V4h-5M4 15v5h5M20 15v5h-5"/></svg> Full screen <kbd>F</kbd>`);
  fs.onclick = goFull;
  right.appendChild(fs);
  const cur = vs.find(v => v.id === S.view);
  const own = el('a', 'linkbtn', 'Own window &nearr;');
  own.href = docURL(cur.doc); own.target = '_blank'; own.rel = 'noopener';
  right.appendChild(own);
  bar.appendChild(right);
  head.appendChild(bar);

  mountFrames(L, vs);
  $('#fsbtns').innerHTML = '';
  vs.filter(v => v.doc).forEach(v => {
    const b = el('button', v.id === S.view ? 'on' : '', esc(v.label));
    b.onclick = () => setView(v.id);
    $('#fsbtns').appendChild(b);
  });
}

/** Mount every document of this lesson once, toggle by [hidden].  Never
 *  destroy — a reloaded iframe loses all interactive state. */
function mountFrames(L, vs) {
  const box = $('#frames');
  if (box.dataset.slug !== L.slug) { box.innerHTML = ''; box.dataset.slug = L.slug; }
  vs.forEach(v => {
    if (!v.doc) return;
    let f = box.querySelector(`iframe[data-v="${v.id}"]`);
    if (!f) {
      f = document.createElement('iframe');
      f.dataset.v = v.id;
      f.setAttribute('allowfullscreen', '');
      // aria-label, not title: a title attribute renders a native tooltip that
      // floats over the full-screen control pill.
      f.setAttribute('aria-label', `${L.title} — ${v.label}`);
      f.hidden = true;
      box.appendChild(f);
    }
    if (v.id === S.view && !f.src) f.src = docURL(v.doc) + (S.anchor ? '#' + S.anchor : '');
    f.hidden = v.id !== S.view;
  });
  S.anchor = null;
}

function renderGuide() {
  const u = S.units[S.ui], p = $('#pane');
  p.innerHTML = '';
  p.appendChild(el('h1', 'pg', esc(unitTitle(u))));
  p.appendChild(el('p', 'pgsub', esc(unitSub(u))));
  p.appendChild(el('p', 'note',
    'The packet is the required work &mdash; everything in <b>Extra practice</b> is optional. ' +
    'Page numbers are printed pages in Stewart, <i>Calculus</i>, 8th edition.'));

  const t = el('table', 'guide',
    `<thead><tr><th style="width:28%">Lesson</th><th style="width:15%">Stewart</th>
     <th>Extra practice</th><th style="width:14%;text-align:right">Materials</th></tr></thead>`);
  const tb = el('tbody');
  (u.guide || []).forEach(row => {
    if (row.kind === 'banner') return;
    if (row.kind === 'break') {
      tb.appendChild(el('tr', 'gbreak', `<td colspan="4">${esc(row.text)}</td>`)); return;
    }
    if (row.kind !== 'lesson') {
      tb.appendChild(el('tr', row.kind === 'exam' ? 'grow-assess grow-exam' : 'grow-assess',
        `<td>${esc(row.name)}</td><td>${esc(row.stewart || '')}</td>
         <td>${esc(row.hw || '')}</td><td style="text-align:right">${esc(row.date || '')}</td>`));
      return;
    }
    const entry = S.lessons.find(x => x.u === u && S.guideFor.get(x.L) === row);
    const L = entry && entry.L;
    const tr = el('tr', L ? 'click' : '',
      `<td><div class="gname"${L ? '' : ' style="color:var(--ink-4)"'}>${esc(row.name)}</div>
           <div class="gcode">${esc(L ? L.code + ' · ' + (row.date || '') : row.date || '')}</div></td>
       <td style="color:var(--ink-3)">${esc(row.stewart || '')}</td>
       <td style="color:var(--ink-2);line-height:1.6">${esc(row.hw || '')}${row.count ? ` <span style="color:var(--ink-4)">(${row.count})</span>` : ''}</td>
       <td style="text-align:right"></td>`);
    const cell = tr.lastElementChild;
    if (L) {
      viewsOf(L).filter(v => v.doc).slice(0, 2).forEach((v, k) => {
        if (k) cell.appendChild(el('span', '', ' <span style="color:#cbd5e1">&middot;</span> '));
        const a = el('button', 'docl', esc(v.label));
        a.style.color = k ? 'var(--ink-3)' : 'var(--accent)';
        a.onclick = e => { e.stopPropagation(); S.view = v.id; pick(S.lessons.indexOf(entry)); };
        cell.appendChild(a);
      });
      tr.onclick = () => pick(S.lessons.indexOf(entry));
    } else {
      cell.innerHTML = '<span style="color:var(--ink-4);font-size:11.5px">not yet</span>';
    }
    tb.appendChild(tr);
  });
  t.appendChild(tb);
  p.appendChild(t);
  p.scrollTop = 0;
}

function renderNet() {
  const pill = $('#netpill'), txt = $('#nettext');
  if (S.pending) {                       // something new is published, not yet loaded
    pill.className = 'pillstat new';
    txt.textContent = 'New lessons ready';
    return;
  }
  if (S.offline || !navigator.onLine) {
    pill.className = 'pillstat off';
    txt.textContent = S.savedAll ? 'Offline · saved' : 'Offline';
    return;
  }
  // "Checked ..." is a claim we can actually support; "Up to date" was not.
  pill.className = 'pillstat';
  txt.textContent = 'Checked ' + (S.lastCheck ? ago(S.lastCheck) : 'just now');
}

/* ═════════════════════════════════════════════════════ behaviour ══ */

function pick(i) {
  S.li = i; S.mode = 'doc';
  S.ui = S.units.indexOf(S.lessons[i].u);
  S.open.add(S.lessons[i].u.unit);
  localStorage.setItem('open', JSON.stringify([...S.open]));
  localStorage.setItem('last', JSON.stringify({ slug: S.lessons[i].L.slug, view: S.view }));
  render();
  refreshCached().then(() => { renderRail(); renderFoot(); });
}
function setView(v) {
  S.view = v;
  localStorage.setItem('last', JSON.stringify({ slug: S.lessons[S.li].L.slug, view: v }));
  renderReader();
}
function cycleView(back) {
  const vs = viewsOf(S.lessons[S.li].L).filter(v => v.doc);
  const k = vs.findIndex(v => v.id === S.view);
  setView(vs[(k + (back ? vs.length - 1 : 1)) % vs.length].id);
}
function goFull() {
  if (S.mode !== 'doc') return;
  S.full = true; render();
  const r = $('#reader');
  if (r.requestFullscreen) r.requestFullscreen().catch(() => {});
}
function exitFull() {
  S.full = false; render();
  if (document.fullscreenElement) document.exitFullscreen().catch(() => {});
}
document.addEventListener('fullscreenchange', () => {
  if (!document.fullscreenElement && S.full) { S.full = false; render(); }
});

/* ── search ── */

/* Fold accents and apostrophes off BOTH sides before matching.
   L'Hopital was effectively unfindable: nobody types the circumflex, and the
   index carries two different apostrophes for the same lesson -- the Quarto's
   typographic one in "L’Hôpital’s Rule" and the schedule's straight one in
   "1.9 L'Hôpital's Rule". Folding both makes hopital, l'hopital, lhopital
   and L’Hôpital all find it. */
const sfold = s => String(s)
  .normalize('NFD').replace(/[\u0300-\u036f]/g, '')          // H\u00f4pital -> Hopital
  .replace(/[\u2018\u2019\u02bc\u0060\u0027]/g, '')       // every apostrophe variant
  .toLowerCase();

function buildHits(q) {
  q = sfold(q.trim());
  if (!q) return [];
  const out = [];
  for (const { L, u } of S.lessons) {
    if (sfold(L.title).includes(q))
      out.push({ kind: 'lesson', L, u, t: L.title, s: `${L.code}${L.stewart ? ' · §' + L.stewart.replace(/^§/, '') : ''}` });
    for (const sec of L.sections)
      if (sfold(sec.text).includes(q))
        out.push({ kind: 'section', L, u, id: sec.id, t: sec.text, s: `${L.title} · ${L.code}` });
  }
  for (const u of S.units)
    for (const row of (u.guide || []))
      if (row.kind === 'lesson' && sfold(row.hw || '').includes(q))
        out.push({ kind: 'guide', u, t: `${row.name} — homework`, s: row.hw });
  return out.slice(0, 12);
}
/* Hover must NOT repaint. paintHits() replaces every row node, so a repaint
   landing between mousedown and mouseup destroys the row the press started on;
   the browser then fires `click` on the nearest common ancestor -- #results,
   which has no handler -- and the hit is simply unclickable. That is what Ryan
   hit 2026-08-26: typing a query listed results, and clicking one did nothing.
   Selection now only toggles a class, so the row under the cursor survives. */
let hitEls = [];
function markSel(scroll) {
  hitEls.forEach((b, i) => b.classList.toggle('sel', i === S.hi));
  if (scroll && hitEls[S.hi]) hitEls[S.hi].scrollIntoView({ block: 'nearest' });
}
function paintHits() {
  const box = $('#results');
  hitEls = [];
  if (!S.hits.length) {
    box.innerHTML = $('#search').value.trim() ? '<div class="empty">Nothing matches that.</div>' : '';
    box.classList.toggle('open', !!$('#search').value.trim());
    return;
  }
  const q = $('#search').value.trim();
  const mark = s => esc(s).replace(new RegExp('(' + q.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + ')', 'ig'), '<em>$1</em>');
  box.innerHTML = '';
  S.hits.forEach((h, i) => {
    const ic = h.kind === 'section'
      ? '<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M5 7h14M5 12h9M5 17h11"/></svg>'
      : h.kind === 'guide'
      ? '<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 5h16v14H4z"/><path d="M4 10h16M4 15h16"/></svg>'
      : '<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 5h16v14H4z"/><path d="M8 5v14"/></svg>';
    const b = el('button', 'hit' + (i === S.hi ? ' sel' : ''),
      `<span class="ic">${ic}</span><span style="min-width:0;flex:1"><b>${mark(h.t)}</b><span>${mark(h.s)}</span></span>
       ${h.kind === 'section' ? '<span style="font-size:10.5px;color:var(--ink-4)">jump to heading</span>' : ''}`);
    b.onmouseenter = () => { if (S.hi !== i) { S.hi = i; markSel(); } };
    b.onmousedown = e => e.preventDefault();   // keep the caret in the search box
    b.onclick = () => openHit(i);
    box.appendChild(b);
    hitEls.push(b);
  });
  box.classList.add('open');
}
function openHit(i) {
  const h = S.hits[i];
  if (!h) return;
  closeSearch();
  if (h.kind === 'guide') { S.ui = S.units.indexOf(h.u); S.mode = 'guide'; render(); return; }
  if (h.kind === 'section') { S.anchor = h.id; S.view = 'quarto'; }
  const idx = S.lessons.findIndex(x => x.L === h.L);
  const box = $('#frames');
  if (h.kind === 'section' && box.dataset.slug === h.L.slug) {
    const f = box.querySelector('iframe[data-v="quarto"]');
    if (f) { f.src = docURL(h.L.quarto) + '#' + h.id; S.anchor = null; }
  }
  pick(idx);
}
function closeSearch() {
  $('#search').value = ''; S.hits = []; S.hi = 0; hitEls = [];
  $('#results').classList.remove('open'); $('#search').blur();
}

/* ── keyboard ── */
addEventListener('keydown', e => {
  const typing = document.activeElement === $('#search');
  if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'b') {
    e.preventDefault(); S.slim = !S.slim; localStorage.setItem('slim', S.slim ? '1' : '0'); render(); return;
  }
  if (e.key === 'Escape') {
    if ($('#help').classList.contains('open')) return $('#help').classList.remove('open');
    if (typing || $('#results').classList.contains('open')) return closeSearch();
    if (S.full) exitFull();
    return;
  }
  if (typing) {
    if (e.key === 'ArrowDown') { e.preventDefault(); S.hi = (S.hi + 1) % Math.max(1, S.hits.length); markSel(true); }
    else if (e.key === 'ArrowUp') { e.preventDefault(); S.hi = (S.hi - 1 + S.hits.length) % Math.max(1, S.hits.length); markSel(true); }
    else if (e.key === 'Enter') { e.preventDefault(); openHit(S.hi); }
    return;
  }
  if (e.metaKey || e.ctrlKey || e.altKey) return;
  if (e.key === '/') { e.preventDefault(); $('#search').focus(); }
  else if (e.key === '?') { $('#help').classList.toggle('open'); }
  else if (e.key === 'f' || e.key === 'F') { S.full ? exitFull() : goFull(); }
  else if ((e.key === 'g' || e.key === 'G') && !S.full) { S.mode = 'guide'; render(); }
  else if (e.key === 'Tab') { e.preventDefault(); if (S.mode === 'doc') cycleView(e.shiftKey); }
  else if (e.key === 'ArrowDown') { e.preventDefault(); pick(Math.min(S.li + 1, S.lessons.length - 1)); }
  else if (e.key === 'ArrowUp') { e.preventDefault(); pick(Math.max(S.li - 1, 0)); }
  else if (e.key === 'u' || e.key === 'U') {          // next unit
    const n = (S.ui + 1) % S.units.length;
    S.open.add(S.units[n].unit); S.ui = n; S.mode = 'guide';
    localStorage.setItem('open', JSON.stringify([...S.open])); render();
  }
});

/* ── wiring ── */
$('#search').addEventListener('input', () => { S.hits = buildHits($('#search').value); S.hi = 0; paintHits(); });
$('#search').addEventListener('focus', () => { if ($('#search').value) paintHits(); });
$('#railbtn').onclick = () => { S.slim = !S.slim; localStorage.setItem('slim', S.slim ? '1' : '0'); render(); };
$('#helpbtn').onclick = () => $('#help').classList.toggle('open');
$('#help').onclick = e => { if (e.target.id === 'help') $('#help').classList.remove('open'); };
$('#keys').innerHTML = KEYS.map(([k, d]) => `<div class="krow"><span>${d}</span><kbd>${k}</kbd></div>`).join('');
addEventListener('online',  () => { S.offline = false; renderNet(); checkForUpdates(true); });
addEventListener('offline', () => { S.offline = true;  renderNet(); });
// Coming back to the app is the moment a student would expect it to have noticed.
document.addEventListener('visibilitychange', () => { if (!document.hidden) checkForUpdates(); });
addEventListener('focus', () => checkForUpdates());
// Keeps "Checked 5 min ago" honest without polling the network.
// The 08-19 fix gave freshness a refocus trigger and an online trigger, but no
// timer -- so an app that stays VISIBLE and online never re-fetched the
// manifest at all. That is the docked-during-class case, and Ryan hit it the
// first time a publish landed while the window was in front of him.
// checkForUpdates() already self-throttles to 60s, so this cannot hammer.
// Tick at 20s, NOT 60s. checkForUpdates() self-throttles to 60s (see its
// lastCheck guard), so a 60s interval races its own throttle and gets dropped
// -- verified: with the periods equal, the tick never got through. Ticking
// faster than the throttle lets the throttle be the real rate limiter, which
// lands a genuine check about once a minute.
setInterval(() => { renderNet(); if (!document.hidden) checkForUpdates(); }, 20000);
$('#toastbtn').onclick = () => location.reload();

function toast(msg) { $('#toastmsg').textContent = msg; $('#toast').classList.add('open'); }

if ('serviceWorker' in navigator) {
  navigator.serviceWorker.register('sw.js').then(reg => {
    reg.addEventListener('updatefound', () => {
      const w = reg.installing;
      w && w.addEventListener('statechange', () => {
        if (w.state === 'installed' && navigator.serviceWorker.controller)
          toast('A new version of the app is ready.');
      });
    });
  }).catch(() => {});
}

load();
