/* Calculus — PWA shell.
   Reads index.json (generated by admin/pwa/deploy.py) and presents it as the
   "Binder": a rail of units and lessons, a reader that never navigates away.

   Two decisions that are load-bearing, both documented in
   admin/reference/student_site_plan.md 8:

   1. Documents are addressed by CONTENT: q/foo.html?h=<hash>.  A changed
      document is therefore a different URL, so a plain cache-first service
      worker is always correct and there is no hash bookkeeping anywhere.
   2. The four documents of the open lesson are mounted at once and toggled by
      visibility, never torn down.  Destroying an iframe reloads it, which would
      reset every slider in a Quarto's interactives.
*/
'use strict';

const CACHE_DOCS = 'calc-docs-v1';
const VIEWS = [
  { id: 'quarto',   label: 'Quarto',      hint: 'the full write-up, with the interactives' },
  { id: 'packet',   label: 'Packet',      hint: 'the questions you worked in class' },
  { id: 'ticket',   label: 'Entry ticket', hint: '' },
  { id: 'onepager', label: 'One-pager',   hint: 'the keeper' },
];
const KEYS = [
  ['/', 'Search'], ['&uarr; &darr;', 'Move between lessons'], ['&crarr;', 'Open'],
  ['Tab', 'Next document'], ['&#8984;B', 'Retract the sidebar'], ['F', 'Full screen'],
  ['G', 'Unit guide'], ['Esc', 'Back out'], ['?', 'This list'],
];

const $ = s => document.querySelector(s);
const el = (t, c, h) => { const n = document.createElement(t); if (c) n.className = c;
                          if (h != null) n.innerHTML = h; return n; };
const esc = s => String(s).replace(/[&<>"]/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;' }[c]));

const S = {                       // application state
  data: null, units: [], lessons: [], guideFor: new Map(),
  ui: 0, li: 0, view: 'quarto', mode: 'doc',
  slim: localStorage.getItem('slim') === '1',
  full: false, offline: false, cached: new Set(), hits: [], hi: 0,
};

/* ══════════════════════════════════════════════════════════ data ══ */

const docURL = d => d ? `${d.file}?h=${d.hash.slice(0, 12)}` : null;

function viewsOf(L) {
  return VIEWS.map(v => ({ ...v, doc: v.id === 'quarto' ? L.quarto : L.docs[v.id] }));
}

/** Pair each lesson with its row in the unit guide.  The guide is authoritative
 *  for Stewart sections and homework — some Quartos' <meta name="lesson"> carries
 *  the folder code rather than the textbook section. */
function linkGuide(unit) {
  for (const L of unit.lessons) {
    const code = L.code.replace(/^L/, '');
    const row = (unit.guide || []).find(r => r.kind === 'lesson' &&
      (r.name || '').replace(/\s+/g, ' ').trim().startsWith(code + ' '));
    if (row) {
      S.guideFor.set(L, row);
      L.stewart = row.stewart || L.stewart;
      L.date = row.date;
    }
  }
}

async function load() {
  let json;
  try {
    const r = await fetch('index.json', { cache: 'no-cache' });
    if (!r.ok) throw new Error(r.status);
    S.offline = r.headers.get('X-From-Cache') === '1';
    json = await r.json();
  } catch (e) {
    const c = await caches.match('index.json');
    if (!c) {
      $('#bootmsg').textContent = navigator.onLine
        ? 'Could not load the course. Try again in a moment.'
        : 'You are offline, and this device has not downloaded the course yet. Connect once and it will work offline afterwards.';
      return;
    }
    json = await c.json();
    S.offline = true;
  }
  S.data = json;
  S.units = json.units || [];
  S.units.forEach(linkGuide);
  S.lessons = S.units.flatMap(u => u.lessons.map(L => ({ L, u })));
  if (!S.lessons.length) {
    $('#bootmsg').textContent = S.offline
      ? 'Nothing downloaded on this device yet. Reconnect once.'
      : 'No lessons published yet.';
    return;
  }

  const last = JSON.parse(localStorage.getItem('last') || 'null');
  if (last) {
    const i = S.lessons.findIndex(x => x.L.slug === last.slug);
    if (i >= 0) { S.li = i; S.ui = S.units.indexOf(S.lessons[i].u); S.view = last.view || 'quarto'; }
  }
  await refreshCached();
  $('#boot').remove();
  render();
}

async function refreshCached() {
  S.cached = new Set();
  if (!('caches' in window)) return;
  try {
    const c = await caches.open(CACHE_DOCS);
    for (const req of await c.keys()) S.cached.add(new URL(req.url).pathname.split('/').slice(-2).join('/'));
  } catch (e) { /* private mode */ }
}
const isCached = d => d && S.cached.has(d.file.split('/').slice(-2).join('/'));

/* ══════════════════════════════════════════════════════════ rail ══ */

function render() {
  document.body.classList.toggle('slim', S.slim);
  document.body.classList.toggle('full', S.full);
  renderRail(); renderFoot(); renderReader(); renderNet();
}

function renderRail() {
  const wide = $('#wide'), slim = $('#slim');
  wide.innerHTML = ''; slim.innerHTML = '';

  S.units.forEach((u, ui) => {
    const active = S.mode === 'guide' && ui === S.ui;
    const head = el('button', 'unithead' + (active ? ' on' : ''),
      `<b>${esc(unitTitle(u))}</b><span>Unit guide &amp; homework &rarr;</span>`);
    head.onclick = () => { S.ui = ui; S.mode = 'guide'; render(); };
    wide.appendChild(head);

    const gi = el('button', 'srow' + (active ? ' on' : ''),
      `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 5h16v14H4z"/><path d="M4 10h16M4 15h16"/></svg>`);
    gi.onclick = head.onclick;
    tipify(gi, unitTitle(u), 'unit guide & homework');
    slim.appendChild(gi);
    slim.appendChild(el('div', 'sep'));

    (u.guide && u.guide.length ? u.guide : u.lessons.map(L => ({ kind: 'lesson', _L: L })))
      .forEach(row => railRow(u, row, wide, slim));
  });
}

function railRow(u, row, wide, slim) {
  if (row.kind === 'break') {
    wide.appendChild(el('div', 'brk', esc(row.text || '')));
    slim.appendChild(el('div', 'sep'));
    return;
  }
  if (row.kind === 'banner') return;

  if (row.kind !== 'lesson') {                       // quiz / review / exam
    const exam = row.kind === 'exam';
    wide.appendChild(el('div', 'assess' + (exam ? ' exam' : ''),
      `<span>${esc(row.name)}</span><span style="opacity:.6;font-weight:400">${esc(row.date || '')}</span>`));
    const b = el('div', 'srow', `<span class="sbar${exam ? ' exam' : ''}"></span>`);
    tipify(b, row.name, row.date || '');
    slim.appendChild(b);
    return;
  }

  const L = row._L || S.lessons.find(x => x.u === u && S.guideFor.get(x.L) === row)?.L;
  if (!L) {                                          // scheduled, not published yet
    wide.appendChild(el('div', 'assess',
      `<span style="color:var(--ink-4);font-weight:400">${esc(row.name)}</span>
       <span style="opacity:.5;font-weight:400">${esc(row.date || '')}</span>`));
    slim.appendChild(el('div', 'srow', `<span class="sbar" style="background:#eef2f6"></span>`));
    return;
  }

  const i = S.lessons.findIndex(x => x.L === L);
  const on = S.mode === 'doc' && i === S.li;
  const ok = isCached(L.quarto);
  const r = el('button', 'lrow' + (on ? ' on' : ''),
    `<span class="lcode">${esc(L.code)}</span>
     <span class="lmeta"><span class="ltitle">${esc(L.title)}</span>
     <span class="lsub">${esc(L.stewart ? '§' + L.stewart.replace(/^§/, '') : '')}</span></span>
     <span class="dot ${ok ? '' : 'pale'}" style="margin-top:5px"></span>`);
  r.onclick = () => pick(i);
  wide.appendChild(r);

  const s = el('button', 'srow' + (on ? ' on' : ''),
    `<span class="scode">${esc(L.code.replace(/^L/, ''))}</span><span class="dot ${ok ? '' : 'pale'}"></span>`);
  s.onclick = () => pick(i);
  tipify(s, L.title, `${L.code}${L.stewart ? ' · §' + L.stewart.replace(/^§/, '') : ''}`);
  slim.appendChild(s);
}

/** "unit1-review" -> "Unit 1 · Review".  The guide's banner is the subtitle,
 *  not the title — it is a full sentence and reads as shouting in the rail. */
const unitTitle = u => u.unit.replace(/^unit(\d+)-?/, 'Unit $1 · ')
  .split('·').map(s => s.trim().replace(/\b\w/g, c => c.toUpperCase())).join(' · ');
const unitSub = u => ((u.guide || []).find(r => r.kind === 'banner')?.text || '')
  .replace(/^REVIEW:\s*/i, '').trim();

/** The rail scrolls, so an absolutely-positioned tooltip inside it is clipped
 *  by overflow-x.  One shared fixed element, positioned on hover, instead. */
function tipify(node, title, sub) {
  node.onmouseenter = () => {
    if (!S.slim) return;
    const t = $('#tip'), r = node.getBoundingClientRect();
    t.innerHTML = `<b>${esc(title)}</b><span>${esc(sub)}</span>`;
    t.style.display = 'block';
    t.style.left = (r.right + 10) + 'px';
    t.style.top = Math.max(8, r.top + r.height / 2 - t.offsetHeight / 2) + 'px';
  };
  node.onmouseleave = () => { $('#tip').style.display = 'none'; };
}

function renderFoot() {
  const u = S.units[S.ui];
  const files = u.lessons.flatMap(L => [L.quarto, ...Object.values(L.docs)]);
  const have = files.filter(isCached).length;
  S.savedAll = have === files.length;
  const mb = files.reduce((a, f) => a + f.bytes, 0) / 1e6;
  const b = $('#savebtn');
  b.innerHTML = have === files.length
    ? `<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 6L9 17l-5-5"/></svg> Saved for offline`
    : `<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 3v12m0 0l-4-4m4 4l4-4M4 19h16"/></svg> Save this unit <small>${mb.toFixed(0)} MB</small>`;
  b.disabled = have === files.length;
  b.onclick = () => saveUnit(u, files);
}

async function saveUnit(u, files) {
  const b = $('#savebtn');
  b.disabled = true;
  let done = 0;
  for (const f of files) {
    try { await fetch(docURL(f)); } catch (e) { /* keep going */ }
    done++;
    b.innerHTML = `Saving&hellip; <small>${done} of ${files.length}</small>`;
  }
  await refreshCached();
  render();
}

/* ════════════════════════════════════════════════════════ reader ══ */

function renderReader() {
  $('#pane').hidden = S.mode !== 'guide';
  $('#frames').style.display = S.mode === 'guide' ? 'none' : '';
  $('#dochead').style.display = S.mode === 'guide' ? 'none' : '';
  if (S.mode === 'guide') { renderGuide(); return; }

  const { L } = S.lessons[S.li];
  const vs = viewsOf(L);
  if (!vs.find(v => v.id === S.view && v.doc)) S.view = 'quarto';

  const head = $('#dochead');
  head.innerHTML = '';
  head.appendChild(el('div', 'crumb', esc(unitTitle(S.lessons[S.li].u))));
  head.appendChild(el('h1', 'doc', esc(L.title)));
  head.appendChild(el('div', 'docmeta',
    `<b>${esc(L.code)}</b><span>&middot;</span>${L.stewart ? '<span>§' + esc(L.stewart.replace(/^§/, '')) + '</span><span>&middot;</span>' : ''}
     <span>${esc(L.date || '')}</span>`));

  const bar = el('div', 'toolbar');
  const seg = el('div', 'seg');
  vs.forEach(v => {
    const b = el('button', v.id === S.view ? 'on' : '', esc(v.label));
    b.disabled = !v.doc;
    b.title = v.doc ? v.hint : 'not published';
    b.onclick = () => setView(v.id);
    seg.appendChild(b);
  });
  bar.appendChild(seg);
  bar.appendChild(el('kbd', '', 'Tab'));

  const right = el('div', 'spacer');
  const fs = el('button', 'linkbtn',
    `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 9V4h5M20 9V4h-5M4 15v5h5M20 15v5h-5"/></svg> Full screen <kbd>F</kbd>`);
  fs.onclick = goFull;
  right.appendChild(fs);
  const cur = vs.find(v => v.id === S.view);
  const own = el('a', 'linkbtn', 'Own window &nearr;');
  own.href = docURL(cur.doc); own.target = '_blank'; own.rel = 'noopener';
  right.appendChild(own);
  bar.appendChild(right);
  head.appendChild(bar);

  mountFrames(L, vs);
  $('#fsbtns').innerHTML = '';
  vs.filter(v => v.doc).forEach(v => {
    const b = el('button', v.id === S.view ? 'on' : '', esc(v.label));
    b.onclick = () => setView(v.id);
    $('#fsbtns').appendChild(b);
  });
}

/** Mount every document of this lesson once, toggle by [hidden].  Never
 *  destroy — a reloaded iframe loses all interactive state. */
function mountFrames(L, vs) {
  const box = $('#frames');
  if (box.dataset.slug !== L.slug) { box.innerHTML = ''; box.dataset.slug = L.slug; }
  vs.forEach(v => {
    if (!v.doc) return;
    let f = box.querySelector(`iframe[data-v="${v.id}"]`);
    if (!f) {
      f = document.createElement('iframe');
      f.dataset.v = v.id;
      f.setAttribute('allowfullscreen', '');
      f.title = `${L.title} — ${v.label}`;
      f.hidden = true;
      box.appendChild(f);
    }
    if (v.id === S.view && !f.src) f.src = docURL(v.doc) + (S.anchor ? '#' + S.anchor : '');
    f.hidden = v.id !== S.view;
  });
  S.anchor = null;
}

function renderGuide() {
  const u = S.units[S.ui], p = $('#pane');
  p.innerHTML = '';
  p.appendChild(el('h1', 'pg', esc(unitTitle(u))));
  p.appendChild(el('p', 'pgsub', esc(unitSub(u))));
  p.appendChild(el('p', 'note',
    'The packet is the required work &mdash; everything in <b>Extra practice</b> is optional. ' +
    'Page numbers are printed pages in Stewart, <i>Calculus</i>, 8th edition.'));

  const t = el('table', 'guide',
    `<thead><tr><th style="width:28%">Lesson</th><th style="width:15%">Stewart</th>
     <th>Extra practice</th><th style="width:14%;text-align:right">Materials</th></tr></thead>`);
  const tb = el('tbody');
  (u.guide || []).forEach(row => {
    if (row.kind === 'banner') return;
    if (row.kind === 'break') {
      tb.appendChild(el('tr', 'gbreak', `<td colspan="4">${esc(row.text)}</td>`)); return;
    }
    if (row.kind !== 'lesson') {
      tb.appendChild(el('tr', row.kind === 'exam' ? 'grow-assess grow-exam' : 'grow-assess',
        `<td>${esc(row.name)}</td><td>${esc(row.stewart || '')}</td>
         <td>${esc(row.hw || '')}</td><td style="text-align:right">${esc(row.date || '')}</td>`));
      return;
    }
    const entry = S.lessons.find(x => x.u === u && S.guideFor.get(x.L) === row);
    const L = entry && entry.L;
    const tr = el('tr', L ? 'click' : '',
      `<td><div class="gname"${L ? '' : ' style="color:var(--ink-4)"'}>${esc(row.name)}</div>
           <div class="gcode">${esc(L ? L.code + ' · ' + (row.date || '') : row.date || '')}</div></td>
       <td style="color:var(--ink-3)">${esc(row.stewart || '')}</td>
       <td style="color:var(--ink-2);line-height:1.6">${esc(row.hw || '')}${row.count ? ` <span style="color:var(--ink-4)">(${row.count})</span>` : ''}</td>
       <td style="text-align:right"></td>`);
    const cell = tr.lastElementChild;
    if (L) {
      viewsOf(L).filter(v => v.doc).slice(0, 2).forEach((v, k) => {
        if (k) cell.appendChild(el('span', '', ' <span style="color:#cbd5e1">&middot;</span> '));
        const a = el('button', 'docl', esc(v.label));
        a.style.color = k ? 'var(--ink-3)' : 'var(--accent)';
        a.onclick = e => { e.stopPropagation(); S.view = v.id; pick(S.lessons.indexOf(entry)); };
        cell.appendChild(a);
      });
      tr.onclick = () => pick(S.lessons.indexOf(entry));
    } else {
      cell.innerHTML = '<span style="color:var(--ink-4);font-size:11.5px">not yet</span>';
    }
    tb.appendChild(tr);
  });
  t.appendChild(tb);
  p.appendChild(t);
  p.scrollTop = 0;
}

function renderNet() {
  const pill = $('#netpill'), txt = $('#nettext');
  if (S.offline || !navigator.onLine) {
    pill.className = 'pillstat off';
    txt.textContent = S.savedAll ? 'Offline · saved' : 'Offline';
  }
  else { pill.className = 'pillstat'; txt.textContent = 'Up to date'; }
}

/* ═════════════════════════════════════════════════════ behaviour ══ */

function pick(i) {
  S.li = i; S.mode = 'doc';
  S.ui = S.units.indexOf(S.lessons[i].u);
  localStorage.setItem('last', JSON.stringify({ slug: S.lessons[i].L.slug, view: S.view }));
  render();
  refreshCached().then(() => { renderRail(); renderFoot(); });
}
function setView(v) {
  S.view = v;
  localStorage.setItem('last', JSON.stringify({ slug: S.lessons[S.li].L.slug, view: v }));
  renderReader();
}
function cycleView(back) {
  const vs = viewsOf(S.lessons[S.li].L).filter(v => v.doc);
  const k = vs.findIndex(v => v.id === S.view);
  setView(vs[(k + (back ? vs.length - 1 : 1)) % vs.length].id);
}
function goFull() {
  if (S.mode !== 'doc') return;
  S.full = true; render();
  const r = $('#reader');
  if (r.requestFullscreen) r.requestFullscreen().catch(() => {});
}
function exitFull() {
  S.full = false; render();
  if (document.fullscreenElement) document.exitFullscreen().catch(() => {});
}
document.addEventListener('fullscreenchange', () => {
  if (!document.fullscreenElement && S.full) { S.full = false; render(); }
});

/* ── search ── */
function buildHits(q) {
  q = q.trim().toLowerCase();
  if (!q) return [];
  const out = [];
  for (const { L, u } of S.lessons) {
    if (L.title.toLowerCase().includes(q))
      out.push({ kind: 'lesson', L, u, t: L.title, s: `${L.code}${L.stewart ? ' · §' + L.stewart.replace(/^§/, '') : ''}` });
    for (const sec of L.sections)
      if (sec.text.toLowerCase().includes(q))
        out.push({ kind: 'section', L, u, id: sec.id, t: sec.text, s: `${L.title} · ${L.code}` });
  }
  for (const u of S.units)
    for (const row of (u.guide || []))
      if (row.kind === 'lesson' && (row.hw || '').toLowerCase().includes(q))
        out.push({ kind: 'guide', u, t: `${row.name} — homework`, s: row.hw });
  return out.slice(0, 12);
}
function paintHits() {
  const box = $('#results');
  if (!S.hits.length) {
    box.innerHTML = $('#search').value.trim() ? '<div class="empty">Nothing matches that.</div>' : '';
    box.classList.toggle('open', !!$('#search').value.trim());
    return;
  }
  const q = $('#search').value.trim();
  const mark = s => esc(s).replace(new RegExp('(' + q.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + ')', 'ig'), '<em>$1</em>');
  box.innerHTML = '';
  S.hits.forEach((h, i) => {
    const ic = h.kind === 'section'
      ? '<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M5 7h14M5 12h9M5 17h11"/></svg>'
      : h.kind === 'guide'
      ? '<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 5h16v14H4z"/><path d="M4 10h16M4 15h16"/></svg>'
      : '<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 5h16v14H4z"/><path d="M8 5v14"/></svg>';
    const b = el('button', 'hit' + (i === S.hi ? ' sel' : ''),
      `<span class="ic">${ic}</span><span style="min-width:0;flex:1"><b>${mark(h.t)}</b><span>${mark(h.s)}</span></span>
       ${h.kind === 'section' ? '<span style="font-size:10.5px;color:var(--ink-4)">jump to heading</span>' : ''}`);
    b.onmouseenter = () => { S.hi = i; paintHits(); };
    b.onclick = () => openHit(i);
    box.appendChild(b);
  });
  box.classList.add('open');
}
function openHit(i) {
  const h = S.hits[i];
  if (!h) return;
  closeSearch();
  if (h.kind === 'guide') { S.ui = S.units.indexOf(h.u); S.mode = 'guide'; render(); return; }
  if (h.kind === 'section') { S.anchor = h.id; S.view = 'quarto'; }
  const idx = S.lessons.findIndex(x => x.L === h.L);
  const box = $('#frames');
  if (h.kind === 'section' && box.dataset.slug === h.L.slug) {
    const f = box.querySelector('iframe[data-v="quarto"]');
    if (f) { f.src = docURL(h.L.quarto) + '#' + h.id; S.anchor = null; }
  }
  pick(idx);
}
function closeSearch() {
  $('#search').value = ''; S.hits = []; S.hi = 0;
  $('#results').classList.remove('open'); $('#search').blur();
}

/* ── keyboard ── */
addEventListener('keydown', e => {
  const typing = document.activeElement === $('#search');
  if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'b') {
    e.preventDefault(); S.slim = !S.slim; localStorage.setItem('slim', S.slim ? '1' : '0'); render(); return;
  }
  if (e.key === 'Escape') {
    if ($('#help').classList.contains('open')) return $('#help').classList.remove('open');
    if (typing || $('#results').classList.contains('open')) return closeSearch();
    if (S.full) exitFull();
    return;
  }
  if (typing) {
    if (e.key === 'ArrowDown') { e.preventDefault(); S.hi = (S.hi + 1) % Math.max(1, S.hits.length); paintHits(); }
    else if (e.key === 'ArrowUp') { e.preventDefault(); S.hi = (S.hi - 1 + S.hits.length) % Math.max(1, S.hits.length); paintHits(); }
    else if (e.key === 'Enter') { e.preventDefault(); openHit(S.hi); }
    return;
  }
  if (e.metaKey || e.ctrlKey || e.altKey) return;
  if (e.key === '/') { e.preventDefault(); $('#search').focus(); }
  else if (e.key === '?') { $('#help').classList.toggle('open'); }
  else if (e.key === 'f' || e.key === 'F') { S.full ? exitFull() : goFull(); }
  else if ((e.key === 'g' || e.key === 'G') && !S.full) { S.mode = 'guide'; render(); }
  else if (e.key === 'Tab') { e.preventDefault(); if (S.mode === 'doc') cycleView(e.shiftKey); }
  else if (e.key === 'ArrowDown') { e.preventDefault(); pick(Math.min(S.li + 1, S.lessons.length - 1)); }
  else if (e.key === 'ArrowUp') { e.preventDefault(); pick(Math.max(S.li - 1, 0)); }
});

/* ── wiring ── */
$('#search').addEventListener('input', () => { S.hits = buildHits($('#search').value); S.hi = 0; paintHits(); });
$('#search').addEventListener('focus', () => { if ($('#search').value) paintHits(); });
$('#railbtn').onclick = () => { S.slim = !S.slim; localStorage.setItem('slim', S.slim ? '1' : '0'); render(); };
$('#helpbtn').onclick = () => $('#help').classList.toggle('open');
$('#help').onclick = e => { if (e.target.id === 'help') $('#help').classList.remove('open'); };
$('#keys').innerHTML = KEYS.map(([k, d]) => `<div class="krow"><span>${d}</span><kbd>${k}</kbd></div>`).join('');
addEventListener('online', renderNet); addEventListener('offline', renderNet);
$('#toastbtn').onclick = () => location.reload();

function toast(msg) { $('#toastmsg').textContent = msg; $('#toast').classList.add('open'); }

if ('serviceWorker' in navigator) {
  navigator.serviceWorker.register('sw.js').then(reg => {
    reg.addEventListener('updatefound', () => {
      const w = reg.installing;
      w && w.addEventListener('statechange', () => {
        if (w.state === 'installed' && navigator.serviceWorker.controller)
          toast('A new version of the app is ready.');
      });
    });
  }).catch(() => {});
}

load();
